name:                pl-h
version:             0.1.0.0
github:              "orange.lihai/pl-h"
license:             BSD3
author:              "orange.lihai"
maintainer:          "orange.lihai"
copyright:           "2018 orange.lihai"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/orange.lihai/pl-h#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  pl-h-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pl-h

tests:
  pl-h-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pl-h
